stages:
  process:
    cmd: python src/imageProcess.py
    deps:
      - src/imageProcess.py
      - dataset/unprocessed/downloaded/archive
    outs:
      - dataset/processed/a
      - dataset/processed/e
      - dataset/processed/i
      - dataset/processed/o
      - dataset/processed/u
      - dataset/processed/ka
      - dataset/processed/ke
      - dataset/processed/ki
      - dataset/processed/ko
      - dataset/processed/ku

  update-dataset:
    cmd: python updateDataset.py
    outs:
      - dataset.h5

  prepare:
    cmd: python src/prepare.py
    deps:
      - dataset.h5
      - dataset/processed/a
      - dataset/processed/e
      - dataset/processed/i
      - dataset/processed/o
      - dataset/processed/u
      - dataset/processed/ka
      - dataset/processed/ke
      - dataset/processed/ki
      - dataset/processed/ko
      - dataset/processed/ku

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - dataset.h5
    outs:
      - model.h5

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - model.h5
      - dataset.h5
