prepare:
  seed: 77
  split: 0.2
  image_size: [64, 64]
  grayscale: True

train:
  seed: 77
  lr: 0.0001
  epochs: 10
  conv_size1: 32        
  conv_size2: 64        
  dense_size: 128       
  output_classes: 11
  