MODEL_TITLE = "hiragana_classifier_model"
MODEL_PATH = "model"
PATH_CREDENTIAL = "mlops-project-machledata-3657a44f4ecf.json"
BUCKET_NAME = "png-dataset-processed"
PROJECT_ID = "mlops-project-machledata"